### ISSUE TITLE
feat: add a "About Us" or "Teams" page

### ISSUE THREAD

**Issue by AyanavaKarmakar** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#130]
### Is your feature request related to a problem? Please describe.

requires further discussion in [discord](https://discord.com/invite/xxSXWYf6d4). Priority: **LOW**.

### Describe the solution you'd like to see

N/A

### Describe alternate solutions

N/A

**Comment by debroopghosh11** [comment]
Hi @AyanavaKarmakar I would like to work on this issue under Hacktoberfest. Could you please provide me more information about this issue wrt the design.

**Comment by wriddhi** [comment]
> Hi @AyanavaKarmakar I would like to work on this issue under Hacktoberfest. Could you please provide me more information about this issue wrt the design.

Hey Debroop, I am a core maintainer of this repo and I would like to take up this issue myself since it's scope is quite large and we want to establish some well-defined and opinionated code structuring patterns here. Since you are new to our project, I would like you to handle some smaller bug-fix or enhancement issues that will help you get familiar with the project 🎉

**Comment by debroopghosh11** [comment]
Hey @wriddhi Thanks a lot for letting me know. I surely would want to get familiar with the project first and then make bigger fixes/enhancements as well. 
As of now could you please let me know any issues which you have in mind which as good first and up for grabs
