### ISSUE TITLE
feat: add more screen space in "Home" tab

### ISSUE THREAD

**Issue by AyanavaKarmakar** [Pujo-Atlas-Kolkata/PujoAtlasKol-Web#157]

**Comment by vsnikhilvs** [comment]
Please comment on what you have in your mind clearly

**Comment by wriddhi** [comment]
> Please comment on what you have in your mind clearly

Hey @vsnikhilvs, this issue was about optimizing the UI by implementing design changes as a lot of unneccessary space was taken by unimportant texts and headings at the top,  thus reducing the amount of actual useful content visible below it. 

We considered this a considerable improvement in UX, so I handled it myself as a core maintainer. You can join our discord and take up any other open issues. We are also expecting to post some more bugs and issues in the coming days as our app is finally being used by real users and thus in a beta testing phase.
